import {
  DashboardIcon,
  EmployeeIcon,
  LeaveIcon,
  PayrollIcon,
  AttendanceIcon,
  PerformanceIcon,
  GrievanceIcon,
  LearningIcon,
  ReportIcon,
  BriefcaseIcon,
} from '@/components/Icons';
import { NavigationItem } from '@/types/navigation';

export const navigationItems: NavigationItem[] = [
  {
    name: 'Dashboard',
    path: '/dashboard',
    icon: <DashboardIcon size={20} />,
  },
  {
    name: 'Employees',
    path: '/employees',
    icon: <EmployeeIcon size={20} />,
    subMenu: [
      { name: 'All Employees', path: '/employees', description: 'View all employees' },
      { name: 'Departments', path: '/employees/departments', description: 'Manage departments' },
      { name: 'Positions', path: '/employees/positions', description: 'Manage job positions' },
      { name: 'Org Chart', path: '/employees/org-chart', description: 'Organization hierarchy' },
      { name: 'Exit Management', path: '/employees/exit', description: 'Offboarding process' },
    ],
  },
  {
    name: 'Leave',
    path: '/leave',
    icon: <LeaveIcon size={20} />,
    subMenu: [
      { name: 'Leave Requests', path: '/leave', description: 'View leave applications' },
      { name: 'Leave Calendar', path: '/leave/calendar', description: 'Team leave overview' },
      { name: 'Leave Policies', path: '/leave/policies', description: 'Leave rules & quotas' },
      { name: 'Leave Balance', path: '/leave/balance', description: 'Check your balance' },
      { name: 'Holidays', path: '/leave/holidays', description: 'Public holidays list' },
    ],
  },
  {
    name: 'Payroll',
    path: '/payroll',
    icon: <PayrollIcon size={20} />,
    subMenu: [
      { name: 'Payroll Overview', path: '/payroll', description: 'Monthly payroll summary' },
      { name: 'Run Payroll', path: '/payroll/run', description: 'Process monthly payroll' },
      { name: 'Salary Structure', path: '/payroll/structure', description: 'Manage salary components' },
      { name: 'Tax Management', path: '/payroll/tax', description: 'Tax calculations & filing' },
      { name: 'Payslips', path: '/payroll/payslips', description: 'Generate & view payslips' },
      { name: 'Bonuses', path: '/payroll/bonuses', description: 'Manage bonuses & incentives' },
    ],
  },
  {
    name: 'Attendance',
    path: '/attendance',
    icon: <AttendanceIcon size={20} />,
    subMenu: [
      { name: 'All Records', path: '/attendance/all-records', description: 'View all attendance records' },
      { name: 'Check In/Out', path: '/attendance/checkin', description: 'Mark your attendance' },
      { name: 'Attendance Logs', path: '/attendance/logs', description: 'Daily attendance logs' },
      { name: 'Schedules', path: '/attendance/schedules', description: 'View work schedules' },
      { name: 'Timesheet', path: '/attendance/timesheet', description: 'Track work hours' },
      { name: 'Shifts', path: '/attendance/shifts', description: 'Manage work shifts' },
      { name: 'Overtime', path: '/attendance/overtime', description: 'Overtime requests' },
      { name: 'Attendance Reports', path: '/attendance/reports', description: 'Attendance analytics' },
    ],
  },
  {
    name: 'Performance',
    path: '/performance',
    icon: <PerformanceIcon size={20} />,
    subMenu: [
      { name: 'Performance Reviews', path: '/performance', description: 'Appraisal cycles' },
      { name: 'Goal Setting', path: '/performance/goals', description: 'Set & track OKRs' },
      { name: '360° Feedback', path: '/performance/feedback', description: 'Peer reviews' },
      { name: 'KPI Dashboard', path: '/performance/kpi', description: 'Key performance indicators' },
      { name: 'Development Plans', path: '/performance/development', description: 'Career development' },
      { name: 'Ratings', path: '/performance/ratings', description: 'Performance ratings' },
    ],
  },
  {
    name: 'Grievances',
    path: '/grievances',
    icon: <GrievanceIcon size={20} />,
    subMenu: [
      { name: 'All Grievances', path: '/grievances', description: 'View all complaints' },
      { name: 'Grievance Analytics', path: '/grievances/analytics', description: 'Issue trends' },
      { name: 'Resolution Center', path: '/grievances/resolution', description: 'Resolve issues' },
    ],
  },
  {
    name: 'Learning',
    path: '/learning',
    icon: <LearningIcon size={20} />,
    subMenu: [
      { name: 'Learning Management', path: '/learning', description: 'Manage all courses' },
      { name: 'My Courses', path: '/learning/courses', description: 'Enrolled courses' },
      { name: 'Course Catalog', path: '/learning/catalog', description: 'Browse all courses' },
      { name: 'Training Calendar', path: '/learning/calendar', description: 'Upcoming sessions' },
      { name: 'Certifications', path: '/learning/certifications', description: 'Track certifications' },
      { name: 'Learning Paths', path: '/learning/paths', description: 'Career tracks' },
      { name: 'Skills Matrix', path: '/learning/skills', description: 'Skill assessments' },
    ],
  },
  {
    name: 'Reports',
    path: '/reports',
    icon: <ReportIcon size={20} />,
    subMenu: [
      { name: 'Reports & Analytics', path: '/reports', description: 'Reports dashboard with analytics' },
      { name: 'Headcount Reports', path: '/reports/headcount', description: 'Employee statistics' },
      { name: 'Payroll Reports', path: '/reports/payroll', description: 'Salary analytics' },
      { name: 'Attendance Reports', path: '/reports/attendance', description: 'Attendance analytics' },
      { name: 'Performance Reports', path: '/reports/performance', description: 'Performance metrics' },
      { name: 'Report Builder', path: '/reports/builder', description: 'Build custom reports' },
      { name: 'Org Structure', path: '/reports/org-structure', description: 'Organization hierarchy' },
      { name: 'Escalation Time', path: '/reports/escalation-time', description: 'Track escalation timelines' },
      { name: 'Audit Trail', path: '/reports/audit-trail', description: 'System activity logs' },
    ],
  },
  {
    name: 'Recruitment',
    path: '/recruitment',
    icon: <BriefcaseIcon size={20} />,
    subMenu: [
      { name: 'Job Postings', path: '/recruitment/jobs', description: 'Manage job openings' },
      { name: 'Applicants', path: '/recruitment/applicants', description: 'Review candidates' },
      { name: 'Interviews', path: '/recruitment/interviews', description: 'Schedule interviews' },
      { name: 'Offers', path: '/recruitment/offers', description: 'Manage job offers' },
      { name: 'Onboarding', path: '/recruitment/onboarding', description: 'New hire onboarding' },
      { name: 'Talent Pool', path: '/recruitment/talent-pool', description: 'Candidate database' },
    ],
  },
];
